### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by denis-vk** [ashishbhate/bcsearch#2]
python3 local_resources_runner.py
==========
Traceback (most recent call last):
  File "local_resources_runner.py", line 25, in <module>
    addresses_dict = get_addresses_from_vanitygen(VANITYGEN_PATH, 10)
  File "/home/ubuntu/bcsearch/bcsearch/addresses.py", line 40, in get_addresses_from_vanitygen
    timeout=timeout, universal_newlines=True)
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/vanitygen/'

**Comment by ashishbhate** [comment]
I think there may be file permission issues with your setup. Check that you have vanitygen installed correctly and that the constants file points to the correct vanitygen binary file.
